### ISSUE TITLE
Collect sample frequent phrases

### ISSUE THREAD

**Issue by shield-9** [beaconFUN/youbeacomm-server#11]
We need more phrases for `/phrase/suggestions/frequent/`.

*This issue should be closed if 10+ phrases posted here.*

**Comment by shield-9** [comment]
- Cloud you take a picture?
- Where is the nearest toilet?
- Can I use free Wi-Fi here?

**Comment by Kawada74** [comment]
・Could you tell me the recommended restaurant?
・What is famous in Hakodate?
・Do they eat sushi everyday in Japan?
・What Japanese food should I try?
・I’d like to go to Hakodate station.
・What time is the next bus?
・Where is the convenience store nearby?
・Is it all right even if I drink water in Japan?
・What time does here close?
・Is the food in Japan good?
・How are manners in Japan?
・Can the Japanese taxi driver speak English?
・Where is it possible for the exchange?
・Where is the tourist information center?
・Please tell me how to get on trains.


参考にしたサイト：
https://english-hacker.jp/472/
http://eikaiwa-highway.com/faq-abroad/
http://juken.oricon.co.jp/rank_english/news/2079251/
http://www.mlit.go.jp/kankocho/news08_000233.html

**Comment by Kawada74** [comment]
あと夏休み中に、いろんなサイトから「よく聞かれる質問」について調べていたので、それも一応乗せておきます（日本語ですが）。以降載せるものは、前回私の投稿の中に含まれているものと含まれていないものがあります。

-------------------------------memo--------------------------------------
＜道を尋ねる＞
・△△の場所・行き方を教えて欲しい
・この辺りに□□があるのか教えて欲しい

＜食べ物＞
・日本の食べ物は美味しいですか？
・日本料理は辛いですか？
・日本では外国料理が食べられますか？
・日本で水を飲んでも大丈夫ですか？
・おすすめの飲食店を教えてください

＜観光＞
・どこに行くのがオススメですか？
・東京から成田までどのくらい時間がかかりますか？

＜乗り物＞
・日本のタクシーの運転手は英語を話せますか？
・新幹線の速さはどれぐらいですか？

＜文化・習慣＞
・日本での礼儀はどのような感じですか？
・お気に入りの漫画はありますか？
・日本式の風呂にはどうのような入り方をしますか？
・日本ではチップをあげますか？
・日本人は床の上に寝るのですか？
・日本では家に入ると、靴を脱ぐのは本当ですか？
・日本の家はどんな造りですか？
・日本では値切りをしますか？
・日本では住宅は高いですか？
・東京では物価が高いですか？
・あなたは仏教の信者ですか？

＜日本人＞
・日本人はどんな感じですか？（性格とか人間性）

---------------------------------------------------------------------------

**Comment by shield-9** [comment]
I'm closing this issue, since minimum requirements are satisfied. But more phrases are welcome!
最低限の条件が満たされたので、このIssueはクローズしますが、まだまだフレーズの提案は歓迎です！

**Comment by yutafujiwara** [comment]
財布を落としてしまいました。
物を盗まれてしまいました。
娘が迷子になりました。
